---
# install and update homebrew and cask

- name: install homebrew
  shell: 'yes | /bin/bash -c $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)' 
  args:
    creates: /usr/local/bin/brew

- name: ensure homebrew is updated 
  homebrew:
    state: latest
    update_homebrew: yes

#- name: tap homebrew caskroom/cask
#  homebrew_tap:
#    tap: "caskroom/cask"

- name: tap homebrew neovim/homebrew-neovim 
  homebrew_tap:
    tap: "neovim/homebrew-neovim"
    state: present

